# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, help_text='Eine genaue Adresse des Vorhabens', max_length=256, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, help_text='Örtliche Beschreibung', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='place',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='places', to='region.Entity', verbose_name='Einheit'),
        ),
        migrations.AlterField(
            model_name='place',
            name='identifier',
            field=models.CharField(blank=True, help_text='ggf. Bezeichner des Beplauungsplans', max_length=64, verbose_name='Bezeichner'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.FloatField(verbose_name='Längengrad'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='hover_icon',
            field=models.CharField(max_length=256, verbose_name='Icon auf der Karte bei Hovereffekt'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='icon',
            field=models.CharField(max_length=256, verbose_name='Icon auf der Karte'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='order',
            field=models.IntegerField(help_text='Nummer in der Reihenfolge', verbose_name='Reihenfolge'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='process_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='process.ProcessType', verbose_name='Verfahren'),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='begin',
            field=models.DateField(verbose_name='Beginn der Auslegungszeit'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='region.Department', verbose_name='Verantwortliche Behörde'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='end',
            field=models.DateField(verbose_name='Ende der Auslegungszeit'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='office',
            field=models.TextField(blank=True, verbose_name='Auslegungsstelle'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='office_hours',
            field=models.TextField(blank=True, verbose_name='Öffnungszeiten der Auslegungsstelle'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='process.Place', verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='process_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='process.ProcessStep', verbose_name='Verfahrensschritt'),
        ),
    ]
