# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_email',
            field=models.CharField(max_length=256, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='Autorin/Author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_url',
            field=models.CharField(blank=True, max_length=256, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='enabled',
            field=models.BooleanField(verbose_name='Freigeschaltet'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Place', verbose_name='Ort'),
        ),
    ]
